feature: allowed origin fn
actix/actix-extras pull request #93
Opened 2020-09-09 20:40 UTC by pldin601

## PR Type

Feature

## PR Checklist
Check your PR fulfills the following:

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [ ] Format code with the latest stable rustfmt

## Overview

2020-09-13 18:06 UTC, robjtede commented on actix-cors/CHANGES.md
> +* Implement `allowed_origin_fn` builder method.
move to unreleased section

2020-09-13 18:06 UTC, robjtede commented on actix-cors/src/lib.rs
> +use core::fmt;
use std::fmt

2020-09-13 18:26 UTC, robjtede requested changes
Also think it'd be good to include some info in the main docs on Cors too. It should be crystal clear to readers that the _fns are called AFTER allowed origin whitelist checks when none have matched.

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
> +use core::fmt;
```suggestion

use std::fmt;
```

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
> +    fn validate_origin_fn(&self, req: &RequestHead) -> bool {
```suggestion
    fn validate_origin_fns(&self, req: &RequestHead) -> bool {
```

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
> +    async fn test_not_allowed_origin_fn() {
This test should include a successful call from example.com origin.

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
> +    async fn test_allowed_origin_fn() {
This test should include a successful call from example.com origin.

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
> +    /// Add an predicate function that will be called on each request if client's `Origin`
```suggestion
    /// Add a predicate function that will be called on each request if client's `Origin`
```

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
nit:

```suggestion
```

2020-09-13 18:26 UTC, robjtede commented on actix-cors/src/lib.rs
> +        return write!(f, "origin_fn");
```suggestion
        write!(f, "origin_fn")
```

2020-09-14 12:12 UTC, pldin601 commented
> Also think it'd be good to include some info in the main docs on Cors too. It should be crystal clear to readers that the _fns are called AFTER allowed origin whitelist checks when none have matched.

Can you suggest me where I can add this documentation exactly?

2020-09-14 12:37 UTC, robjtede commented
> Can you suggest me where I can add this documentation exactly?

On the Cors struct docs, such that it appears on this page at the top: https://docs.rs/actix-cors/0.3.0/actix_cors/struct.Cors.html

2020-09-21 04:35 UTC, Neopallium approved these changes
looks good.

2020-09-24 23:36 UTC, robjtede approved these changes

2020-09-24 23:36 UTC, merged

2020-09-24 23:37 UTC, robjtede commented
Nice feature, thanks for this 👍